host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pip

runtime_environments:
  - name: "ubi8"
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.6"
    recommendation_type: latest

managers:
  - name: info
  - name: version
    configuration:
      maintainers:
        - vpavlin
        - LaVLaS
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true